version: "3.8"
services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "9081:8081"

  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: maik1310
      MYSQL_DATABASE: order_service
      MYSQL_USER: root
      MYSQL_PASSWORD: maik1310
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mariadb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306

volumes:
    mariadb: { }